Name:           ros-indigo-usb-cam
Version:        0.3.0
Release:        0%{?dist}
Summary:        ROS usb_cam package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/usb_cam
Source0:        %{name}-%{version}.tar.gz

Requires:       ffmpeg-devel
Requires:       ros-indigo-camera-info-manager
Requires:       ros-indigo-image-transport
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-std-msgs
Requires:       v4l-utils
BuildRequires:  ffmpeg-devel
BuildRequires:  ros-indigo-camera-info-manager
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-image-transport
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-std-msgs

%description
A ROS Driver for V4L USB Cameras

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jan 26 2015 Russell Toris <rctoris@wpi.edu> - 0.3.0-0
- Autogenerated by Bloom

* Fri Jan 16 2015 Russell Toris <rctoris@wpi.edu> - 0.2.0-0
- Autogenerated by Bloom

* Tue Dec 02 2014 Russell Toris <rctoris@wpi.edu> - 0.1.13-0
- Autogenerated by Bloom

* Wed Nov 05 2014 Russell Toris <rctoris@wpi.edu> - 0.1.12-0
- Autogenerated by Bloom

* Thu Oct 30 2014 Russell Toris <rctoris@wpi.edu> - 0.1.11-0
- Autogenerated by Bloom

* Thu Oct 30 2014 Russell Toris <rctoris@wpi.edu> - 0.1.11-1
- Autogenerated by Bloom

* Fri Oct 24 2014 Russell Toris <rctoris@wpi.edu> - 0.1.10-0
- Autogenerated by Bloom

* Tue Aug 26 2014 Russell Toris <rctoris@wpi.edu> - 0.1.9-0
- Autogenerated by Bloom

* Thu Aug 21 2014 Russell Toris <rctoris@wpi.edu> - 0.1.8-0
- Autogenerated by Bloom

* Wed Aug 20 2014 Russell Toris <rctoris@wpi.edu> - 0.1.7-0
- Autogenerated by Bloom

* Fri Aug 15 2014 Russell Toris <rctoris@wpi.edu> - 0.1.6-0
- Autogenerated by Bloom

